version: '3'
services:
  web:
    build: .
    command: foreman start
    ports:
      - "4001:4001"
    depends_on:
      - db
    entrypoint: ./entrypoint.sh
  db:
    image: postgres
    volumes:
     - ./tmp/db:/var/lib/postgresql/data
